import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import Providers from '@/components/Providers/Providers';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers>
        <body className={`${inter.className} antialiased flex`}>
          <div className='w-[80px] min-h-screen h-full bg-[#D9D9D9]'></div>
          <div className='w-full'>
            <Header />
            <main className='px-10 py-16'>{children}</main>
          </div>
        </body>
      </Providers>
    </html>
  );
}
